rails_app/config/routes.rb
RailsApp::Application.routes.draw do
  

  resources :posts

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'
	
	match '/posts', to: 'posts#show'
	match '/new_post', to: 'posts#new'

  root to: 'pages#home'
  match '/contact', to: 'pages#contact'
  match '/about', to: 'pages#about'
 
  match '/help', to: 'pages#help'

end

rails_app/app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user 
  attr_accessible :content, :title
end

rails_app/app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_secure_password
  attr_accessible :email, :name, :password, :password_confirmation

  before_save { |user| user.email = email.downcase }
  
	validates :password, presence: true, length: { minimum: 8, maximum: 16 }
	validates :password_confirmation, presence: true

  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
end

rails_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  # include SessionsHelper
	before_filter :authorize_user

	protected
	def authorize_user
		return true if current_user.nil?
		session.clear
		redirect_to root_path
		false
	end

  private

	def current_user
	  @current_user ||= User.find_by_id(session[:user_id])
	end
	helper_method :current_user

	def authorize
	  redirect_to login_url, alert: "Not authorized" if current_user.nil?
	end
end

rails_app/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
		@title = "Home"
  end

  def contact
		@title = "Contact"
  end

	def about
		@title = "About"
	end

	def help
		@title = "Help"
	end

	def signin
		@title = "Sign in"
	end
end

rails_app/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @posts }
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @post = Post.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    @post = Post.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @post }
    end
  end

  # GET /posts/1/edit
  def edit
    @post = Post.find(params[:id])
  end

  # POST /posts
  # POST /posts.json
  def create
		@user = current_user
    @post = @user.posts.new(params[:post])

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render json: @post, status: :created, location: @post }
      else
        format.html { render action: "new" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    @post = Post.find(params[:id])

    respond_to do |format|
      if @post.update_attributes(params[:post])
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end
end

rails_app/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    @title = "Sign in"
  end
  
  def create
    user = User.find_by_email(params[:email].downcase)
    if user && user.authenticate(params[:password])
      # sign_in user
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
    	flash.now.alert = "Invalid email/password combination."
      render 'new' 
    end
  end
  
  def destroy
    # sign_out
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged out!"
  end
end

rails_app/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(params[:user])
  	if @user.save
      session[:user_id] = @user.id
  		redirect_to root_url, notice: "Welcome to your Erica's List account."
  	else
  		render 'new'
  	end
  end

  def edit
    @user = User.find(params[:id])
  end

  def show
  	@user = User.find(params[:id])
  end

  def destroy
    # TODO - fill out the crud
  end
end

rails_app/app/helpers/application_helper.rb
module ApplicationHelper

	def full_title(page_title)
		base_title = "Erica's List"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

rails_app/app/helpers/pages_helper.rb
module PagesHelper
end

rails_app/app/helpers/posts_helper.rb
module PostsHelper
end

rails_app/app/helpers/sessions_helper.rb
module SessionsHelper

	# def sign_in(user)
	# 	session[:remember_token] = user.remember_token
 #  end
  
  # def current_user=(user)
  #   @current_user = user
  # end
  
  # def current_user
  #   @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  # end
  
  # def signed_in?
  #   !current_user.nil?
  # end
  
  # def sign_out
  #   session[:remember_token] = nil
  # end

  # def current_user?(user)
  #   user == current_user
  # end

	# def authenticate
 #    deny_access unless signed_in?
 #  end

 #  def deny_access
 #    store_location
 #    redirect_to signin_path, :notice => "Please sign in to access this page."
 #  end

 #  def redirect_back_or(default)
 #    redirect_to(session[:return_to] || default)
 #    clear_return_to
 #  end

 #  private

 #  def remember_token
 #      cookies.signed[:remember_token] || [nil, nil]
 #    end

 #    def store_location
 #      session[:return_to] = request.fullpath
 #    end

 #    def clear_return_to
 #      session[:return_to] = nil
 #    end
end

rails_app/app/helpers/users_helper.rb
module UsersHelper

	# Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

rails_app/app/views/layouts/_footer.html.erb
<footer class="footer">
  <!-- Need to pull this logic out of the view and have the user pass the value to the view -->
  <% if current_user %>
    Logged in as <%= current_user.email %>
  <% else %>
    Not logged in
  <% end %>
</footer>

rails_app/app/views/layouts/_header.html.haml
%header.navbar.navbar.navbar-inverse
  .navbar-inner
    .container-fluid
      %a.btn.btn-navbar{"data-toggle" => "collapse", "data-target" => ".nav-collapse"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to "Erica's List", '/', id: "logo"
      .nav-collapse.pull-right
        %ul.nav
          %li= link_to "All Posts", posts_path unless current_page? posts_path
          / need to remove this logic from the view and have user controller pass array with
          / the dynamic links to be displayed in the view
          - if current_user
            %li= link_to "Create Post", new_post_path unless current_page? new_post_path 
            %li= link_to "Profile", current_user unless current_page? current_user
            %li= link_to "Log out", session_path("current"), method: "delete"
          - else
            %li= link_to "Log in", new_session_path
            %li= link_to "Sign up", new_user_path

rails_app/app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

rails_app/app/views/layouts/_user_form.html.erb
<%= form_for @user do |f| %>
	<%= render 'shared/error_messages' %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.text_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>

  <%= f.submit @button_label, class: "btn btn-large btn-primary" %>
<% end %>

rails_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title><%= full_title(yield(:title)) %></title>
	
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
  <script src="http://code.jquery.com/jquery-1.9.1.min.js"></script>
  <%= render 'layouts/shim' %>
</head>
<body>
  <%= render 'layouts/header' %> 
    <div class="container">
    	<% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
		<%= yield %>
	</div>
	<%= render 'layouts/footer' %>

  <!-- Playing around with JQuery -->
  <script src='../assets/javascripts/myjavascript.js' ></script>

  <!-- Debug statements for development environment only! -->
  <p><%= debug(params) if Rails.env.development? %></p>
	<p><%= debug @user if Rails.env.development? %></p>
	<p><%= debug current_user if Rails.env.development? %></p>
  <p><%= debug @current_page if Rails.env.development? %></p>

</body>
</html>

rails_app/app/views/pages/about.html.haml
<div class="center hero-unit">
%h1 About

%p This is an open source web app being devloped from the idea of Erica Heinz 
%p “I wish there were an Angie’s List for designers and developers, where we could warn each other about bad clients/vendors.”  – @ericaheinz

rails_app/app/views/pages/contact.html.erb
<div class="center hero-unit">
	<h1>Contact</h1>
	<p>Any questions or comments contact the developer @myappleguy</p>

rails_app/app/views/pages/help.html.erb
<div class="center hero-unit">
	<h1>Help</h1>
	<p>If you need help using this then find the devleloper on twitter</p>

rails_app/app/views/pages/home.html.erb
<div class="center hero-unit">
	<h1>Erica's List</h1>
	<p> Developers and Designers client review board. It's like glass door for clients.</p>
	<% if !current_user %>
	<%= link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary" %> 
	<% end %>

rails_app/app/views/pages/signin.html.erb
<div class="center hero-unit">
	<h1>Sign in</h1>
	<p>This is where users will be able to sign in</p>

	

rails_app/app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!--
  <div class="field">
    <%= f.label :author %>
		<%= f.text_field :author %>
		 need this to save user name || user email in with form -->
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br />
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails_app/app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

rails_app/app/views/posts/index.html.erb
<h1>Listing posts</h1>

<table>
  <tr>
    <th>Author</th>
    <th>Title</th>
    <th>Content</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @posts.each do |post| %>
  <tr>
    <td><%= post.author %></td>
    <td><%= post.title %></td>
    <td><%= post.content %></td>
    <td><%= link_to 'Show', post %></td>
    <td><%= link_to 'Edit', edit_post_path(post) %></td>
    <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Post', new_post_path %>

rails_app/app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

rails_app/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Author:</b>
  <%= @post.author %>
</p>

<p>
  <b>Title:</b>
  <%= @post.title %>
</p>

<p>
  <b>Content:</b>
  <%= @post.content %>
</p>


<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

rails_app/app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

rails_app/app/views/users/edit.html.erb
	<div class="row">
	  <div class="span6 offset3">
	  	<h1>Update your profile</h1>
	  	<% @button_label = "Save changes" %>
	    <%= render 'layouts/user_form' %>
	    <%= gravatar_for @user %>
    	<a href="http://gravatar.com/emails">change</a>
	  </div>
	</div>
<div class="center">

rails_app/app/views/users/new.html.erb
	<div class="row">
	  <div class="span6 offset3">
	  	<h1>Sign up</h1>
	  	<% @button_label = "Create my account" %>
	    <%= render 'layouts/user_form' %>
	  </div>
	</div>
<div class="center">

rails_app/app/views/users/show.html.erb
	<div class="row">
	  <aside class="span4">
	    <section>
				<%= gravatar_for @user %><h1><%= @user.name %></h1>
			</section>
	  </aside>
	</div>
<div class="center hero-unit">